"""Generate reports/validation_summary.md from the sample dataset.

Runs the validation engine against data/sample/*.csv and writes a
human-readable markdown summary of findings.
"""

from __future__ import annotations

import os
import sys
from collections import Counter, defaultdict

# Ensure the package is importable when running the script directly.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from retail_ops_control_tower.io import read_all_csv_tables
from retail_ops_control_tower.validation import validate_tables

SAMPLE_DIR = "data/sample"
REPORT_PATH = "reports/validation_summary.md"


def main() -> int:
    tables = read_all_csv_tables(SAMPLE_DIR)
    report = validate_tables(tables)

    by_rule: Counter[str] = Counter(f.rule_code for f in report.findings)
    by_severity_table: Counter[tuple[str, str]] = Counter(
        (f.severity, f.table) for f in report.findings
    )
    by_table_rule: dict[str, Counter[str]] = defaultdict(Counter)
    for f in report.findings:
        by_table_rule[f.table][f.rule_code] += 1

    rule_descriptions = {
        "VAL-01": "Required column checks",
        "VAL-02": "Duplicate key checks",
        "VAL-03": "Foreign key checks",
        "VAL-04": "Planned vs dispatched variance",
        "VAL-05": "Planned vs received variance",
        "VAL-06": "Dispatch without plan",
        "VAL-07": "Confirmation without dispatch",
        "VAL-08": "Photo proof without confirmation",
        "VAL-09": "Sales record without campaign/store match",
    }

    lines: list[str] = []
    lines.append("# Validation Summary")
    lines.append("")
    lines.append("Generated by running the T09 validation engine against the sample")
    lines.append("dataset in `data/sample/` (100 stores, 3 campaigns, 1,410 allocation")
    lines.append("lines). The engine implements 9 data-quality and planned-vs-actual")
    lines.append("reconciliation rules. Each finding is a structured record with")
    lines.append("severity, table, row id, rule code, message, and suggested action.")
    lines.append("")
    lines.append("## Overall")
    lines.append("")
    lines.append(f"- Total findings: **{report.total}**")
    lines.append(f"- Critical: **{report.critical_count}**")
    lines.append(f"- Warning: **{report.warning_count}**")
    lines.append(f"- Info: **{report.info_count}**")
    lines.append("")
    lines.append("## Tables validated")
    lines.append("")
    lines.append("| Table | Rows |")
    lines.append("|-------|------|")
    for name, count in sorted(report.table_row_counts.items()):
        lines.append(f"| {name} | {count} |")
    lines.append("")
    lines.append("## Findings by rule")
    lines.append("")
    lines.append("| Rule | Description | Count |")
    lines.append("|------|-------------|-------|")
    for code in sorted(rule_descriptions):
        lines.append(f"| {code} | {rule_descriptions[code]} | {by_rule.get(code, 0)} |")
    lines.append("")
    lines.append("## Findings by severity and table")
    lines.append("")
    lines.append("| Severity | Table | Count |")
    lines.append("|----------|-------|-------|")
    for (severity, table), count in sorted(by_severity_table.items()):
        lines.append(f"| {severity} | {table} | {count} |")
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    if report.critical_count == 0:
        lines.append("- **Referential integrity is intact.** No duplicate primary keys, no")
        lines.append("  orphaned foreign keys, no dispatch rows without an allocation plan")
        lines.append("  row, no confirmations without a dispatch, and no photo proofs")
        lines.append("  without a confirmation. This confirms the sample data generator")
        lines.append("  (T08) produces internally consistent data.")
    else:
        lines.append("- **Critical findings present.** Referential integrity issues were")
        lines.append("  detected and should be resolved before downstream exception")
        lines.append("  management runs.")
    if by_rule.get("VAL-04", 0) > 0 or by_rule.get("VAL-05", 0) > 0:
        lines.append("- **Quantity variances are expected.** The generator deliberately")
        lines.append("  short-ships (88-100% of planned) and injects ~12% receiving")
        lines.append("  mismatches (shortage, overage, damage, substitution), so VAL-04")
        lines.append("  and VAL-05 warnings are by design. These feed the exception")
        lines.append("  management engine (T10) as `quantity_mismatch` exceptions.")
    lines.append("")
    lines.append("## Sample findings")
    lines.append("")
    lines.append("First 10 findings (sorted by severity, then table, then row id):")
    lines.append("")
    lines.append("| Severity | Rule | Table | Row | Message | Suggested action |")
    lines.append("|----------|------|-------|-----|---------|-------------------|")
    for f in report.findings[:10]:
        msg = f.message.replace("|", "/")
        act = f.suggested_action.replace("|", "/")
        lines.append(f"| {f.severity} | {f.rule_code} | {f.table} | {f.row_id} | {msg} | {act} |")
    lines.append("")
    lines.append("## Rule reference")
    lines.append("")
    for code in sorted(rule_descriptions):
        lines.append(f"- **{code}** - {rule_descriptions[code]}")
    lines.append("")

    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Wrote {REPORT_PATH} ({report.total} findings: {report.critical_count} critical, {report.warning_count} warning)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
